tasks:
  - name: appdev-week1-todolist
    init: |
      cd /workspace/appdev-week1-todolist
      nvm install node
      npm install -g npm@latest
    command: |
      cd /workspace/appdev-week1-todolist
      echo "appdev-week1-todolist gitpod ready - LET'S DO THIS!"
      npm install
ports:
  - port: 8080 # Application
    onOpen: ignore
  - port: 8888 # Webpack dev server
    onOpen: open-browser
github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: false
    addCheck: true
    addComment: false
    addBadge: true
    addLabel: false