tasks:
  - name: appdev-week1-todolist
    init: |
      cd /workspace/appdev-week1-todolist 
      nvm install node
      npm install -g npm@latest
    command: |
      cd /workspace/workshop-astra-tik-tok
      echo "workshop-astra-tik-tok gitpod ready - LET'S DO THIS!"
      npm install
ports:
  - port: 8080 # Application
    onOpen: ignore
  - port: 8888 # Webpack dev server
    onOpen: open-browser
github:
  prebuilds:
    master: true
    branches: false
    pullRequests: false
    pullRequestsFromForks: false
    addCheck: false
    addComment: false
    addBadge: false
    addLabel: false